services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: fleetdb
      POSTGRES_USER: fms
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fms-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fms.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - fms-network

  fleet-service:
    image: fleet-service:latest
    container_name: fleet-service
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/fleetdb
      QUARKUS_DATASOURCE_USERNAME: fms
      QUARKUS_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    networks:
      - fms-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  fms-network:
